// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("rescript/lib/js/js_dict.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");

function $star(a1, a2) {
  return [
          a1,
          a2
        ];
}

var Contact = {};

function apSchema(prim) {
  return prim;
}

function ref(name) {
  return {
          $ref: "#/components/schemas/" + name
        };
}

var Schema = {
  apFalse: false,
  apSchema: apSchema,
  ref: ref
};

function ref$1(name) {
  return {
          $ref: "#/components/parameters/" + name
        };
}

var Parameter = {
  ref: ref$1
};

function ref$2(name) {
  return {
          $ref: "#/components/headers/" + name
        };
}

var Header = {
  ref: ref$2
};

var Example = {};

var MediaType = {};

function ref$3(name) {
  return {
          $ref: "#/components/responses/" + name
        };
}

var $$Response = {
  ref: ref$3
};

function ref$4(name) {
  return {
          $ref: "#/components/securitySchemes/" + name
        };
}

var SecurityScheme = {
  ref: ref$4
};

var License = {};

var Info = {};

var Server = {};

var Operation = {};

var PathItem = {};

var Components = {};

var Tag = {};

function print(t) {
  console.log(Belt_Option.getExn(JSON.stringify(t)));
  
}

var map = Js_dict.fromArray;

exports.map = map;
exports.$star = $star;
exports.Contact = Contact;
exports.Schema = Schema;
exports.Parameter = Parameter;
exports.Header = Header;
exports.Example = Example;
exports.MediaType = MediaType;
exports.$$Response = $$Response;
exports.SecurityScheme = SecurityScheme;
exports.License = License;
exports.Info = Info;
exports.Server = Server;
exports.Operation = Operation;
exports.PathItem = PathItem;
exports.Components = Components;
exports.Tag = Tag;
exports.print = print;
/* No side effect */
